-- MySQL Script generated by MySQL Workbench
-- Tue Oct 21 14:33:48 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pedidos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pedidos` (
  `id_pedido` INT NULL,
  `id_usuario` INT NULL,
  `fecha_hora` DATETIME NULL,
  `total` DECIMAL(10,2) NULL,
  `estado` VARCHAR(45) NULL,
  `id_transaccion_mp` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`detalle_pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`detalle_pedido` (
  `id_detalle` INT NULL,
  `id_pedido` INT NULL,
  `id_producto` INT NULL,
  `precio_unitario` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id_detalle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id_user` INT NULL,
  `email` VARCHAR(255) NULL,
  `password_hash` VARCHAR(32) NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Productos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Productos` (
  `id_producto` INT NULL,
  `name` VARCHAR(45) NULL,
  `descripcion` TEXT NULL,
  `precio` DECIMAL(10,2) NULL,
  `categoria` VARCHAR(45) NULL,
  `image_url` VARCHAR(45) NULL,
  PRIMARY KEY (`id_producto`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
